apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DB_USER: base64-encoded-value  # Preencha no CI: echo -n $DB_USER | base64
  DB_PASSWORD: base64-encoded-value
  DB_ROOT_PASSWORD: base64-encoded-value
  DB_HOST: bXlzcWwtc2VydmljZQ==  # base64 de 'mysql-service'